# Generated by Django 4.2.2 on 2023-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('', 'None'), ('armor and tools', 'Armor and Tools'), ('potions', 'Potions'), ('building blocks', 'Building Blocks'), ('food and farming', 'Food and Farming'), ('resources', 'Resources'), ('utility', 'Utility'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=30),
        ),
    ]
