# Generated by Django 4.2.2 on 2023-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'None'), ('unit', 'Unit'), ('stack', 'Stack')], max_length=20, null=True),
        ),
    ]
