# Generated by Django 4.2.2 on 2023-10-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('diamonds', models.PositiveIntegerField()),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
    ]
