# Generated by Django 4.2.2 on 2023-10-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='user',
        ),
    ]
