# Generated by Django 4.2.2 on 2023-10-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_date_created_alter_order_date_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='cart_total',
        ),
    ]
